// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAVbtPzYh6GYmTyDkTyFwZGsm4zEtPV0M',
    appId: '1:394733669740:web:510f94d8b01a97a9e17749',
    messagingSenderId: '394733669740',
    projectId: 'stock-main',
    authDomain: 'stock-main.firebaseapp.com',
    storageBucket: 'stock-main.appspot.com',
    measurementId: 'G-HCZV0V45G5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD39gFS_cchx0axSOX7ynSMgA6LZkGGvYQ',
    appId: '1:394733669740:android:4a10493be2937d14e17749',
    messagingSenderId: '394733669740',
    projectId: 'stock-main',
    storageBucket: 'stock-main.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_jfrpShi4TIoqtc5sq10nDh-dwD1OdVU',
    appId: '1:394733669740:ios:81c9a6a45e0fecd1e17749',
    messagingSenderId: '394733669740',
    projectId: 'stock-main',
    storageBucket: 'stock-main.appspot.com',
    iosBundleId: 'com.example.stockMain',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_jfrpShi4TIoqtc5sq10nDh-dwD1OdVU',
    appId: '1:394733669740:ios:81c9a6a45e0fecd1e17749',
    messagingSenderId: '394733669740',
    projectId: 'stock-main',
    storageBucket: 'stock-main.appspot.com',
    iosBundleId: 'com.example.stockMain',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDAVbtPzYh6GYmTyDkTyFwZGsm4zEtPV0M',
    appId: '1:394733669740:web:1182d103e99c690fe17749',
    messagingSenderId: '394733669740',
    projectId: 'stock-main',
    authDomain: 'stock-main.firebaseapp.com',
    storageBucket: 'stock-main.appspot.com',
    measurementId: 'G-0EJK1HY8WF',
  );
}
